Document: filedeb
Title: Debian filedeb Manual
Author: <insert document author here>
Abstract: This manual describes what filedeb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/filedeb/filedeb.sgml.gz

Format: postscript
Files: /usr/share/doc/filedeb/filedeb.ps.gz

Format: text
Files: /usr/share/doc/filedeb/filedeb.text.gz

Format: HTML
Index: /usr/share/doc/filedeb/html/index.html
Files: /usr/share/doc/filedeb/html/*.html
